\ wordladder.fs
REQUIRE wl-graph.fs
REQUIRE wl-env.fs

WL-GRAPH G
QUEUE Q

VARIABLE WL-SOURCE
VARIABLE WL-TARGET

: MAIN ( -- )
    NEXT-ARG G WLG-READ-WORDS
    NEXT-ARG 2DUP G CHECK-WORD S>WL-WORD WL-SOURCE !
    NEXT-ARG 2DUP G CHECK-WORD S>WL-WORD WL-TARGET !
    WL-SOURCE @ WL-TARGET @ SWAP Q G WLG-SEARCH-PATH
    IF
        WL-SOURCE @ G .WLG-PATH CR
    ELSE
        ." no path" CR
    THEN ;

MAIN BYE
