\ wordladder.fs
REQUIRE wl-dictionary.fs
REQUIRE wl-env.fs


QUEUE Q
WL-DICTIONARY D

VARIABLE WL-SOURCE
VARIABLE WL-TARGET

: MAIN ( -- )
    NEXT-ARG D WLD-READ-WORDS
    NEXT-ARG 2DUP D CHECK-WORD S>WL-WORD WL-SOURCE !
    NEXT-ARG 2DUP D CHECK-WORD S>WL-WORD WL-TARGET !
    WL-SOURCE @ WL-TARGET @ SWAP Q D WLD-FIND-PATH!
    IF
        WL-SOURCE @ D .WLD-PATH CR
    ELSE
        ." no path" CR
    THEN ;

MAIN BYE
