require ffl/tst.fs
require wordladder.fs
PAGE
T{
    S" aaaaa" S>FLWORD S" aaaab" S>FLWORD <> ?TRUE
    S" cargo" S>FLWORD S" cargo" S>FLWORD = ?TRUE
    S" again" S>FLWORD PAD FLWORD>S PAD 5 S" again" ?STR

    S" CLERK" ADD-WORD
    S" AGAIN" ADD-WORD
    S" LOVER" ADD-WORD

    S" CLERK" IS-WORD? -1 ?S
    S" LOVER" IS-WORD? -1 ?S
    S" CROWN" IS-WORD? 0 ?S

    S" CROWN" S>FLWORD S" CROWD" S>FLWORD NEIGHBOR? ?TRUE
    S" CROWN" S>FLWORD S" BROWN" S>FLWORD NEIGHBOR? ?TRUE
    S" FROWN" S>FLWORD S" DROWN" S>FLWORD NEIGHBOR? ?TRUE
    S" BRAIN" S>FLWORD S" FRAIL" S>FLWORD NEIGHBOR? ?FALSE
}T
BYE
