\ group.fs

REQUIRE small-string.fs

CHAR ~ CONSTANT WILDCARD
7 CELLS CONSTANT INDEX-OFFSET

: NTH-GROUP ( ss,n -- gr )
    DUP -ROT
    [CHAR] ~ SWAP ROT SMALL-STRING-C! 
    SWAP INDEX-OFFSET LSHIFT OR ;

: GROUP-INDEX ( gr -- n )
    INDEX-OFFSET RSHIFT 255 AND ;

: GROUP>WORD ( c,gr -- ss )
    DUP GROUP-INDEX SWAP
    SMALL-STRING-C! ;
