\ wordkey-graph.fs

REQUIRE ffl/hct.fs
REQUIRE wordkey.fs

25000 CONSTANT WORDKEY-GRAPH-SIZE
WORDKEY-GRAPH-SIZE HCT-CREATE WORDKEY-GRAPH

: ADD-START-WORD ( add,l -- )
    0 -ROT WORDKEY-GRAPH HCT-INSERT ;

: PREDECESSOR@>S ( add,l,dest -- )
    -ROT WORDKEY-GRAPH HCT-GET
    0= IF S" unknown word" EXCEPTION THROW THEN
    SWAP WORDKEY>S ;

: ADD-ADJACENT-WORDS ( add,l,add,l -- )
    2SWAP S>WORDKEY -ROT WORDKEY-GRAPH HCT-INSERT ;

: .WORD-PATH ( add,l -- )
    BEGIN
        2DUP TYPE SPACE
        PAD PREDECESSOR@>S
        PAD COUNT DUP
    WHILE
    REPEAT 2DROP ;
