require wordladder.fs

WORD-KEYS ACT-CLEAR
S" CAT" S>WORD-KEY ADD-WORD-KEY
S" CAB" S>WORD-KEY ADD-WORD-KEY
S" COG" S>WORD-KEY ADD-WORD-KEY
S" COT" S>WORD-KEY ADD-WORD-KEY
S" DAB" S>WORD-KEY ADD-WORD-KEY
S" DAG" S>WORD-KEY ADD-WORD-KEY
S" DAM" S>WORD-KEY ADD-WORD-KEY
S" DOC" S>WORD-KEY ADD-WORD-KEY
S" DOG" S>WORD-KEY ADD-WORD-KEY
S" DOT" S>WORD-KEY ADD-WORD-KEY

.WORD-KEYS
bye
